### PR TITLE
Update ss3 with kpa ontology

### PR DESCRIPTION
**Pull request by jesper-friis**
Updated ss3kb to use the KPA ontology. 

Note that this PR builds on top of PR #5.

### CODE REVIEW

**Comment by jesper-friis** [comment]
> Linking between class and KPA is done via restriction on the emmo:hasProperty object.
> 
> ```
> [ 
>     rdf:type owl:Restriction ;
>     owl:onProperty emmo:EMMO_e1097637_70d2_4895_973f_2396f04fa204 ;
>     owl:hasValue :abaqussimulation_accuracy
> ]
> ```
> 
> kpa:hasKPA object should be used instead
> 
> ```
>  [ 
>      rdf:type owl:Restriction ;
>      owl:onProperty <http://open-model.eu/ontoflow/kpa#hasKPA> ;
>      owl:hasValue :abaqussimulation_accuracy
> ]
> ```
> 
> Do you think the definition of the hasKPA is superfluous and we can reuse some already existing property?

I think that it is fine to use `hasKPA`. It is already a subproperty of emmo:hasProperty.

**Comment by francescalb** [comment]
@xAlessandroC I have now updated to hasKPA. Can you check if it is OK?

**Comment by xAlessandroC** [comment]
@francescalb I have checked the new version of the ontology. It seems to be fine, the only point is that the correct KPA namespace binding should be `@prefix kpa: <http://open-model.eu/ontoflow/kpa#> .` instead of `@prefix kpa: <http://open-model.eu/ontoflow/0.1/kpa#>`.

Once this is fixed, we try to run the engine and give you the output. Many thanks!

**Comment by xAlessandroC** [comment]
If you prefer, I can also fix and push to the branch

**Comment by jesper-friis** [comment]
> If you prefer, I can also fix and push to the branch

Feel free to do that. No reasons to wait for us.

**Review by francescalb — APPROVED** [review]

**Pull request merged**
